### ISSUE TITLE
Accept statuss configurable per tracker and per user role.

### ISSUE THREAD

**Issue by janekska** [stefanzugal/accept-plugin#11]
It is often that issue workflows are split between users.
F.ex. one is accepting coders work, than it is going to another, who is accepting testers work, third that is accepting that it is put on production and therefore a bookkeeper can can send a bill.

So it would be very handy, that Accept status could be configurable also per role.

**Comment by stefanzugal** [comment]
I think this makes the plugin too versatiile - it should stay as simple as possible. Also, I do not see the problem of having the same "accept" status here. To "accept" an issue simply means: "now I am working on this" - whatever this may mean in the context of the person.

In our company, we have people developing software - accepting an issue usually means "I am now implementing this feature / fixing this bug". We also have QA / technical writers - they also "accept" tickets, but in their case it usually refers to "I am now writing the documentation".
