### ISSUE TITLE
Data saving problem (version 0.0.2)

### ISSUE THREAD

**Issue by giwlak** [stefanzugal/accept-plugin#12]
Plugin has a problem with Bitnami Redmine version 4.0.4-5. During configuration of a plugin in section of individual status for each tracker, data is not saved. Trackers has special characters like "[" and "]" in its name. When special characters removed - settings were changed.

**Comment by stefanzugal** [comment]
Thank you very much for the bug report - I have reworked the logic for storing the tracker status. In version 0.0.3, this should not be a problem any longer.

**Comment by stefanzugal** [comment]
Oh, should be fixed now.
