### ISSUE TITLE
Redmine 4 and redmine_custom_css plugin incompatibility

### ISSUE THREAD

**Issue by mpauz** [stefanzugal/accept-plugin#14]
When i install accept plugin, all works great, but this plugin is incompatibility with redmine_custom_css
Because i lost all CSS changes.
Im not programmer, but i need both plugins.

**Comment by stefanzugal** [comment]
What do you mean by "losing all CSS changes"? Also, please make sure you have read the Readme on the frontpage to make sure you really need this plugin - there have been some misunderstandings on what this plugin is intended to do (see for example #13).

**Comment by stefanzugal** [comment]
Closing this one due to inactivity.
