### ISSUE TITLE
Disable changing the Assignee

### ISSUE THREAD

**Issue by nixjobin** [stefanzugal/accept-plugin#15]
Hello,

I could see that Status and Assignee are getting changed when the user click Accept.
`Status changed from New to In Progress
Assignee changed from DevOps to User1`

In our workflow, the tickets are assigned to the group (DevOps). So, when the team member clicks Accept, the assignee is getting changed to his name and I want to keep it assigned to the group only. The current issue is that if the assignee is changed, other members won't be able to access that ticket. 

Can you modify the plugin to change the status only and not the assignee ? or have an option to disable changing the assignee on the plugin options.

**Comment by nixjobin** [comment]
Hello @stefanzugal  , Could you please check this?

**Comment by stefanzugal** [comment]
Hi,

sorry, I currently do not have the time to look into this. The plugin is open source - so feel free to have a look on your own :)

Cheers,
Stefan

**Comment by stefanzugal** [comment]
It seems that the intention of the plugin is misleading: the only purpose is to state "I am now working on this issue" - and that should be convienently done with one click.

Therefore, it is not the intention of this plugin to not change the assignee.
