### ISSUE TITLE
Percentage doesn't update in real time

### ISSUE THREAD

**Issue by irongomme** [stefanzugal/accept-plugin#3]
We need to refresh the page to have the percentage updated. I'm using redmine 3.2

**Comment by stefanzugal** [comment]
Actually the plugin submits the redmine form via Javascript, hence the page is reloaded automatically (should be the same behaviour as if you clicked on the "Submit" on the very bottom of the redmine issue). See: https://github.com/stefanzugal/accept-plugin/blob/master/app/helpers/accept_helper.rb#L34

**Comment by irongomme** [comment]
Argh .. this was not for this plugin, i've mixed several pages on github projects. Dont matter about this !
