### ISSUE TITLE
Cannot use this functionnality as a non admin user

### ISSUE THREAD

**Issue by irongomme** [stefanzugal/accept-plugin#4]
With an admin user, eveything works fine, but with a non admin user the accept link is not visible. Do i need to active someting else to make it works ?

**Comment by stefanzugal** [comment]
Admin permissions should not be necessary. However, the plugin will check whether you are listed in the drop-down for assignees. In other words, if your account does not show up in the drop-down listing assignees, the accept button also will not show up. This could also explain why you will see the button when you are logged in as admin.

If your account shows up in the list of assignees, the accept button should also show up. Could you pleasy verify this behaviour?

**Comment by irongomme** [comment]
Ok, I think this a misunderstanding from me, sorry !

What about group assignment, is this possible to change assignement to me by the way of the accept link in the case of the issue is assigned to a group of mines ?

**Comment by stefanzugal** [comment]
That should work. As I wrote, the plugin will allow to accept a ticket, if your account shows up in the list of potential assignees. If the ticket is assigned to a group you are a member of, then redmine should also list your account as potential assignee. Hence, you should be able to accept the ticket.

**Comment by stefanzugal** [comment]
Hmm I guess in this case we can close this issue as well.
