### ISSUE TITLE
New issue state should be tracker specific

### ISSUE THREAD

**Issue by javanthropus** [stefanzugal/accept-plugin#5]
Our Redmine installation has several different trackers defined, and each has a different state that would need to be set when someone accepts the issue.  Would it be possible to extend this plugin to allow for the accepted state to be made dependent on the tracker the issue is in?

**Comment by stefanzugal** [comment]
That sounds like a reasonable extensions. Ideally, it should be configurable whether all trackers have the same "acept" status or whether inidividual accept states are required, something like: radiobutton "individual state per tracker" with yes/no and then the possibility to configure. Also the logic for selecting the appropriate state should be rather easy to extend.

In case I have some spare time left in the near future, I will try to have a look at it.

**Comment by javanthropus** [comment]
This works great on our test rig.  Thanks!  The only thing I might suggest is to use a single checkbox or dropdown listbox to toggle the "individual state per tracker" mode instead of 2 radio buttons.

**Comment by stefanzugal** [comment]
That is good to hear. I would rather stay with the radio buttons - I think it makes it more explicit to the user which options are available. A checkbox can only show one option, for knowing what it means not to select the checkbox requires the user to  think and/or speculate. Of course, that may not be challenging in this case, but still. Regarding dropdowns: here, using radio buttons has the advantage of visually separating between orthogonal options "yes, I want custom states per tracker" and the respective state.

**Comment by javanthropus** [comment]
The checkbox proposal definitely has the problem you mention.  I think you can make the dropdown do what you need though and only expose the options relevant to the selected element of the list.  It's more or less what you're already doing with the radio buttons, but it seems like it might require a little less hacking in the UI code.  Thanks for considering things in any case.

**Comment by stefanzugal** [comment]
That is a good point indeed. I have do admit that I was so focused on the radio buttons - thinking that they would be the best solution - that I did not even consider that. Thanks for the hint!
