### ISSUE TITLE
Internal server error on 3.2.2

### ISSUE THREAD

**Issue by dimon00** [stefanzugal/accept-plugin#8]
When I install the plugin I get error 404 in the accept plugin configuration page while if I try to open a new issue I get "internal server error".

**Comment by stefanzugal** [comment]
It is difficult to make any diagnosis here; basically it should run on Redmine 3.2.x. Have you installed the plugin under your_redmine_base/plugins/accept - so for instance: /var/www/html/redmine_3.2.2/plugins/accept? In this folder, you should then find the folders app, assets config and so on.

If this is the case, could you please provide more information about the 505 error (from the redmine log)?

**Comment by dimon00** [comment]
The problem was with the directory name.
I simply cloned the project the first time.
After renaming the directory to simpy "accept" the problem disappeared.

**Comment by stefanzugal** [comment]
Good to know it is working now. I have updated the readme so hopefully others might not fall into this trap.
