### ISSUE TITLE
Redmine 3.3 Support?

### ISSUE THREAD

**Issue by scharc** [stefanzugal/accept-plugin#9]
Will there be a 3.3.\*  support coming?

**Comment by stefanzugal** [comment]
We are using the plugin in our company - so as soon as we update to redmine 3.3, there will be 3.3.\* support for sure. However, I cannot promise when this will be.

**Comment by archonwang** [comment]
it seems support redmine 3.3.x
I used in my environment 

```
Environment:
  Redmine version                3.3.0.stable.15809
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

**Comment by stefanzugal** [comment]
Great, thanks - I've added it to the readme.

**Comment by stefanzugal** [comment]
@scharc 
Is there anything else you would like to know? If this is not the case, i will close this issue.
